# -*- coding: utf-8 -*-
"""câu 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19baixml2nBx19tUNbcjqLxSGoverC7L6
"""

import cvxpy as cp
import numpy as np
import matplotlib.pyplot as plt

# 1. Khởi tạo tham số
T = 10
rho = 0.97
alpha, gamma, delta, theta, beta = 0.33, 0.10, 0.08, 0.07, 0.42

# Điều kiện ban đầu năm 2026
K0 = 27500.0
L_val = 54.0
D0 = 20.3
AI0 = 86.0
H0 = 30.0
Y0 = 12847.6

# Tính A0
A0 = Y0 / ( (K0**alpha) * (L_val**beta) * (D0**gamma) * (AI0**delta) * (H0**theta) )

# 2. Khai báo biến quyết định
K  = cp.Variable(T+1, nonneg=True)
D  = cp.Variable(T+1, nonneg=True)
AI = cp.Variable(T+1, nonneg=True)
H  = cp.Variable(T+1, nonneg=True)

I_K  = cp.Variable(T, nonneg=True)
I_D  = cp.Variable(T, nonneg=True)
I_AI = cp.Variable(T, nonneg=True)
I_H  = cp.Variable(T, nonneg=True)

C = cp.Variable(T, nonneg=True)
Y = cp.Variable(T, nonneg=True)

# 3. Xây dựng ràng buộc
constraints = [
    K[0] == K0,
    D[0] == D0,
    AI[0] == AI0,
    H[0] == H0,
    C >= 1.0
]

# Trọng số cho geo_mean
weights = np.array([alpha, gamma, delta, theta, beta])

for t in range(T):
    inputs = cp.hstack([K[t], D[t], AI[t], H[t], L_val])
    constraints += [
        Y[t] <= A0 * cp.geo_mean(inputs, p=weights)
    ]

    constraints += [
        C[t] + I_K[t] + I_D[t] + I_AI[t] + I_H[t] <= Y[t]
    ]

    constraints += [
        K[t+1] == (1 - 0.05) * K[t] + I_K[t],
        D[t+1] == (1 - 0.12) * D[t] + I_D[t],
        AI[t+1] == (1 - 0.15) * AI[t] + I_AI[t],
        H[t+1] == (1 - 0.02) * H[t] + 0.8 * I_H[t]
    ]

# 4. Hàm mục tiêu
objective = cp.Maximize(cp.sum([ (rho**t) * cp.log(C[t]) for t in range(T) ]))

# 5. Giải bài toán
# Sử dụng CLARABEL làm solver thay thế cho ECOS/SCS
prob = cp.Problem(objective, constraints)
try:
    prob.solve(solver=cp.CLARABEL)
except Exception as e:
    prob.solve() # Fallback to default if CLARABEL fails

# 6. In kết quả
print(f"Trạng thái tối ưu: {prob.status}")
if prob.status in ["optimal", "optimal_inaccurate", "feasible"]:
    print(f"Tổng phúc lợi: {prob.value:.4f}")

    # Vẽ đồ thị
    plt.figure(figsize=(10, 5))
    plt.plot(range(2026, 2026+T), Y.value, label="Sản lượng (Y)", marker='o')
    plt.plot(range(2026, 2026+T), C.value, label="Tiêu dùng (C)", marker='s')
    plt.title("Quỹ đạo Sản lượng và Tiêu dùng (2026-2035)")
    plt.xlabel("Năm")
    plt.ylabel("Nghìn tỷ VND")
    plt.legend()
    plt.grid(True)
    plt.show()
else:
    print("Không tìm thấy lời giải tối ưu.")

"""### Detailed Visualization of Economic Growth Trajectories
We will now plot the accumulation of different types of capital (K, D, AI, H) and analyze the investment patterns.
"""

import matplotlib.pyplot as plt

# Extract values from CVXPY variables
years_state = range(2026, 2037)  # T+1 years
years_flow = range(2026, 2036)   # T years

val_K = K.value
val_D = D.value
val_AI = AI.value
val_H = H.value
val_Y = Y.value
val_C = C.value
val_IAI = I_AI.value
val_IH = I_H.value

# --- PLOT 1: Capital Stocks and Flow Variables ---
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# Left: State Variables (Capital Stocks)
color_K = 'tab:blue'
ax1.set_xlabel('Năm')
ax1.set_ylabel('Vốn vật chất K (Nghìn tỷ VND)', color=color_K)
ax1.plot(years_state, val_K, marker='o', color=color_K, label='Vốn K', linewidth=2)
ax1.tick_params(axis='y', labelcolor=color_K)

ax1_twin = ax1.twinx()
ax1_twin.set_ylabel('Các loại vốn số hóa (D, AI, H)', color='tab:red')
ax1_twin.plot(years_state, val_D, marker='s', color='tab:orange', label='Hạ tầng số D', linestyle='--')
ax1_twin.plot(years_state, val_AI, marker='^', color='tab:green', label='Năng lực AI', linestyle='--')
ax1_twin.plot(years_state, val_H, marker='d', color='tab:red', label='Vốn nhân lực H', linestyle='--')
ax1_twin.tick_params(axis='y', labelcolor='tab:red')

lines_1, labels_1 = ax1.get_legend_handles_labels()
lines_2, labels_2 = ax1_twin.get_legend_handles_labels()
ax1.legend(lines_1 + lines_2, labels_1 + labels_2, loc='upper left')
ax1.set_title('Quỹ đạo tích lũy Vốn và Công nghệ (2026-2035)')
ax1.grid(True, alpha=0.3)

# Right: Production and Consumption
ax2.plot(years_flow, val_Y, marker='o', color='tab:purple', label='Sản lượng Y', linewidth=2)
ax2.plot(years_flow, val_C, marker='s', color='tab:brown', label='Tiêu dùng C', linewidth=2)
ax2.set_xlabel('Năm')
ax2.set_ylabel('Nghìn tỷ VND')
ax2.set_title('Quỹ đạo Sản lượng và Tiêu dùng (2026-2035)')
ax2.legend(loc='best')
ax2.grid(True, alpha=0.5)

plt.tight_layout()
plt.show()

# --- PLOT 2: Investment Ratio AI/H ---
# Ratio between AI investment and Human Capital investment
# Avoid division by zero by adding a tiny epsilon if needed
ratio_AI_H = val_IAI / (val_IH + 1e-9)

plt.figure(figsize=(8, 4))
plt.plot(years_flow, ratio_AI_H, marker='x', color='tab:red', markersize=8, linewidth=2)
plt.title('Tỷ lệ Đầu tư AI / Đầu tư Nhân lực H (2026-2035)')
plt.xlabel('Năm')
plt.ylabel('Tỷ lệ (I_AI / I_H)')
plt.grid(True, alpha=0.6)
plt.show()

import cvxpy as cp
import numpy as np
import matplotlib.pyplot as plt

# 1. Khởi tạo tham số cơ bản
T = 10
rho = 0.97
alpha, gamma, delta, theta, beta = 0.33, 0.10, 0.08, 0.07, 0.42

K0, L_val, D0, AI0, H0 = 27500.0, 54.0, 20.3, 86.0, 30.0
Y0 = 12847.6
A0 = Y0 / ( (K0**alpha) * (L_val**beta) * (D0**gamma) * (AI0**delta) * (H0**theta) )

# --- THIẾT LẬP CÚ SỐC ---
# TFP shock array: 1.0 (normal), except 2028 (t=2) where it is 0.92 (-8%)
A_shock = np.ones(T)
A_shock[2] = 0.92

# 2. Khai báo biến quyết định
K, D, AI, H = [cp.Variable(T+1, nonneg=True) for _ in range(4)]
I_K, I_D, I_AI, I_H = [cp.Variable(T, nonneg=True) for _ in range(4)]
C, Y = [cp.Variable(T, nonneg=True) for _ in range(2)]

# 3. Xây dựng ràng buộc
constraints = [K[0] == K0, D[0] == D0, AI[0] == AI0, H[0] == H0, C >= 1.0]
weights = np.array([alpha, gamma, delta, theta, beta])

for t in range(T):
    inputs = cp.hstack([K[t], D[t], AI[t], H[t], L_val])

    # Apply TFP shock to production
    constraints += [
        Y[t] <= (A0 * A_shock[t]) * cp.geo_mean(inputs, p=weights)
    ]

    constraints += [
        C[t] + I_K[t] + I_D[t] + I_AI[t] + I_H[t] <= Y[t],
        K[t+1] == (1 - 0.05) * K[t] + I_K[t],
        D[t+1] == (1 - 0.12) * D[t] + I_D[t],
        AI[t+1] == (1 - 0.15) * AI[t] + I_AI[t],
        H[t+1] == (1 - 0.02) * H[t] + 0.8 * I_H[t]
    ]

# 4. Hàm mục tiêu và giải bài toán
objective = cp.Maximize(cp.sum([ (rho**t) * cp.log(C[t]) for t in range(T) ]))
prob_shock = cp.Problem(objective, constraints)
# Clarabel is robust for these shocks
prob_shock.solve(solver=cp.CLARABEL)

# 5. Visualizing Investment Adjustment
years = range(2026, 2036)

plt.figure(figsize=(12, 6))
plt.plot(years, I_K.value, label='Đầu tư Vốn vật chất (I_K)', marker='o')
plt.plot(years, I_D.value, label='Đầu tư Hạ tầng số (I_D)', marker='s')
plt.plot(years, I_AI.value, label='Đầu tư AI (I_AI)', marker='^')
plt.plot(years, I_H.value, label='Đầu tư Nhân lực (I_H)', marker='d')

plt.axvline(x=2028, color='red', linestyle='--', alpha=0.5, label='Năm khủng hoảng (2028)')

plt.title('Điều chỉnh Phân bổ Đầu tư khi chịu cú sốc giảm 8% TFP năm 2028')
plt.xlabel('Năm')
plt.ylabel('Mức đầu tư (Nghìn tỷ VND)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Calculate consumption drop
drop_C = (C.value[1] - C.value[2]) / C.value[1] * 100
print(f"Tiêu dùng (C) năm 2028 giảm {drop_C:.2f}% so với năm 2027 do cú sốc.")

import cvxpy as cp
import numpy as np
import matplotlib.pyplot as plt

def solve_investment_strategy(strategy_type="even"):
    # 1. Khởi tạo tham số cơ bản
    T = 10
    rho = 0.97
    alpha, gamma, delta, theta, beta = 0.33, 0.10, 0.08, 0.07, 0.42

    K0, L_val, D0, AI0, H0 = 27500.0, 54.0, 20.3, 86.0, 30.0
    Y0 = 12847.6
    A0 = Y0 / ( (K0**alpha) * (L_val**beta) * (D0**gamma) * (AI0**delta) * (H0**theta) )

    # 2. Khai báo biến quyết định
    K, D, AI, H = [cp.Variable(T+1, nonneg=True) for _ in range(4)]
    I_K, I_D, I_AI, I_H = [cp.Variable(T, nonneg=True) for _ in range(4)]
    C, Y = [cp.Variable(T, nonneg=True) for _ in range(2)]

    constraints = [K[0] == K0, D[0] == D0, AI[0] == AI0, H[0] == H0, C >= 1.0]
    weights = np.array([alpha, gamma, delta, theta, beta])

    # 3. Ràng buộc hệ thống cơ bản
    for t in range(T):
        inputs = cp.hstack([K[t], D[t], AI[t], H[t], L_val])
        constraints += [
            Y[t] <= A0 * cp.geo_mean(inputs, p=weights),
            C[t] + I_K[t] + I_D[t] + I_AI[t] + I_H[t] <= Y[t],
            K[t+1] == (1 - 0.05) * K[t] + I_K[t],
            D[t+1] == (1 - 0.12) * D[t] + I_D[t],
            AI[t+1] == (1 - 0.15) * AI[t] + I_AI[t],
            H[t+1] == (1 - 0.02) * H[t] + 0.8 * I_H[t]
        ]

    # 4. Ràng buộc định hình chiến lược
    if strategy_type == "even":
        for t in range(T-1):
            constraints += [I_K[t] == I_K[t+1], I_D[t] == I_D[t+1], I_AI[t] == I_AI[t+1], I_H[t] == I_H[t+1]]

    elif strategy_type == "front_load":
        for t in range(2):
            constraints += [I_K[t] == I_K[t+1], I_D[t] == I_D[t+1], I_AI[t] == I_AI[t+1], I_H[t] == I_H[t+1]]
        for t in range(3, T-1):
            constraints += [I_K[t] == I_K[t+1], I_D[t] == I_D[t+1], I_AI[t] == I_AI[t+1], I_H[t] == I_H[t+1]]
        constraints += [
            I_K[2] >= 1.5 * I_K[3], I_D[2] >= 1.5 * I_D[3],
            I_AI[2] >= 1.5 * I_AI[3], I_H[2] >= 1.5 * I_H[3]
        ]

    objective = cp.Maximize(cp.sum([ (rho**t) * cp.log(C[t]) for t in range(T) ]))
    prob = cp.Problem(objective, constraints)
    prob.solve(solver=cp.CLARABEL)

    return prob.value, (I_K.value + I_D.value + I_AI.value + I_H.value), C.value

# --- CHẠY VÀ SO SÁNH ---
welfare_even, inv_even, c_even = solve_investment_strategy("even")
welfare_front, inv_front, c_front = solve_investment_strategy("front_load")

print(f"Welfare Even: {welfare_even:.4f}")
print(f"Welfare Front-load: {welfare_front:.4f}")

years = range(2026, 2036)
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(years, inv_even, label='Even Investment', marker='o')
plt.plot(years, inv_front, label='Front-load Investment', marker='s')
plt.title('Total Investment Comparison')
plt.legend(); plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(years, c_even, label='Consumption (Even)', marker='o')
plt.plot(years, c_front, label='Consumption (Front-load)', marker='s')
plt.title('Consumption Comparison')
plt.legend(); plt.grid(True)
plt.show()