# -*- coding: utf-8 -*-
"""Câu 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14jeot6G9MJB8VgsjNRfQqdWtaP6p9Boy
"""

import cvxpy as cp
import numpy as np
import pandas as pd

# 1. Khởi tạo dữ liệu tham số cho 8 ngành [cite: 634]
N = 8 # [cite: 634]
risk = np.array([18, 42, 25, 38, 52, 35, 28, 22]) / 100 # [cite: 635]
a1 = np.array([8.5, 32.5, 12.8, 22.4, 45.8, 28.5, 62.5, 18.5]) # [cite: 636]
b1 = np.array([45, 28, 35, 32, 22, 30, 20, 55]) # [cite: 637]
c1 = np.array([5.2, 62.4, 18.5, 48.2, 72.5, 42.8, 32.5, 12.5]) # [cite: 638]
d1 = np.array([50, 32, 42, 38, 26, 36, 24, 62]) # [cite: 639]

sectors = [
    "1. Nông-Lâm-Thủy sản", "2. CN chế biến chế tạo",
    "3. Xây dựng", "4. Bán buôn bán lẻ",
    "5. Tài chính-Ngân hàng", "6. Logistics-Vận tải",
    "7. CNTT-Truyền thông", "8. Giáo dục-Đào tạo"
]

# 2. Khai báo vector biến quyết định (ngân sách phân bổ >= 0)
x_AI = cp.Variable(N, nonneg=True) #
x_H = cp.Variable(N, nonneg=True) #

# 3. Tính toán các phương trình tác động lao động
NewJob = cp.multiply(a1, x_AI) #
Upgrade = cp.multiply(b1, x_H) #
Displaced = cp.multiply(cp.multiply(c1, risk), x_AI) #
RetrainCap = cp.multiply(d1, x_H) #
NetJob = NewJob + Upgrade - Displaced #

# 4. Khai báo các ràng buộc
constraints = [
    cp.sum(x_AI + x_H) <= 30000,   # Ràng buộc tổng ngân sách
    NetJob >= 0,                   # Ràng buộc việc làm ròng không âm
    Displaced <= RetrainCap        # Ràng buộc năng lực đào tạo
]

# 5. Thiết lập hàm mục tiêu và giải bài toán
prob = cp.Problem(cp.Maximize(cp.sum(NetJob)), constraints) #
prob.solve() #

# 6. In kết quả theo yêu cầu
print("=== TỔNG QUAN TỐI ƯU HÓA ===")
print(f"Tổng NetJob ròng: {prob.value:,.2f} việc làm")
print(f"Tổng ngân sách đã dùng: {np.sum(x_AI.value) + np.sum(x_H.value):,.2f} tỷ VND\n")

print("=== PHÂN BỔ TỐI ƯU & NETJOB THEO NGÀNH ===")
results = pd.DataFrame({
    "Ngành": sectors,
    "Đầu tư AI (tỷ VND)": x_AI.value,
    "Đầu tư Nhân lực (tỷ VND)": x_H.value,
    "NetJob (việc/tỷ)": NetJob.value
})
print(results.to_string(index=False, float_format="%.2f"))

import numpy as np

# Thông số riêng của ngành 2 (Index 1 trong mảng)
risk_2 = 0.42
c1_2 = 62.4
d1_2 = 32.0
budget = 30000

# Tính tỷ lệ ngưỡng tối thiểu dựa trên ràng buộc Displaced <= RetrainCap
# (c1 * risk * x_AI) <= (d1 * x_H)
displaced_coef = c1_2 * risk_2  # Hệ số mất việc
ratio_H_to_AI = displaced_coef / d1_2  # Tỷ lệ x_H / x_AI tối thiểu

# Tính toán kịch bản đầu tư tối đa vào ngành 2 trong giới hạn tổng ngân sách
# x_AI + x_H = 30000 và x_H = ratio * x_AI
max_x_AI = budget / (1 + ratio_H_to_AI)
min_x_H = budget - max_x_AI

print("=== PHÂN TÍCH CÂU 9.4.2 (NGÀNH CHẾ BIẾN CHẾ TẠO) ===")
print(f"Tỷ lệ đầu tư bắt buộc: 1 đồng AI cần ít nhất {ratio_H_to_AI:.3f} đồng đào tạo nhân lực.")
print(f"Nếu dồn toàn bộ {budget:,} tỷ vào ngành này:")
print(f" -> Ngân sách AI tối đa có thể giải ngân: {max_x_AI:,.2f} tỷ VND")
print(f" -> Ngân sách đào tạo tối thiểu tương ứng: {min_x_H:,.2f} tỷ VND")

import pulp
import pandas as pd
import numpy as np

# 1. Định nghĩa dữ liệu
sectors_list = [
    "1. Nông-Lâm-Thủy sản", "2. CN chế biến chế tạo",
    "3. Xây dựng", "4. Bán buôn bán lẻ",
    "5. Tài chính-Ngân hàng", "6. Logistics-Vận tải",
    "7. CNTT-Truyền thông", "8. Giáo dục-Đào tạo"
]
N = len(sectors_list)

# Các hệ số từ bài tập
risk = np.array([18, 42, 25, 38, 52, 35, 28, 22]) / 100
a1 = np.array([8.5, 32.5, 12.8, 22.4, 45.8, 28.5, 62.5, 18.5])
b1 = np.array([45, 28, 35, 32, 22, 30, 20, 55])
c1 = np.array([5.2, 62.4, 18.5, 48.2, 72.5, 42.8, 32.5, 12.5])
d1 = np.array([50, 32, 42, 38, 26, 36, 24, 62])
TOTAL_BUDGET = 30000

# 2. Khởi tạo bài toán PuLP
model = pulp.LpProblem("Maximize_NetJobs", pulp.LpMaximize)

# 3. Biến quyết định (Ngân sách cho AI và Nhân lực cho mỗi ngành)
x_AI = [pulp.LpVariable(f"x_AI_{i}", lowBound=0) for i in range(N)]
x_H = [pulp.LpVariable(f"x_H_{i}", lowBound=0) for i in range(N)]

# 4. Hàm mục tiêu: Tối đa hóa tổng NetJob
# NetJob_i = a1_i*x_AI_i + b1_i*x_H_i - (c1_i * risk_i * x_AI_i)
net_jobs = [
    (a1[i] - c1[i]*risk[i]) * x_AI[i] + b1[i] * x_H[i]
    for i in range(N)
]
model += pulp.lpSum(net_jobs)

# 5. Ràng buộc
# Tổng ngân sách
model += pulp.lpSum(x_AI + x_H) <= TOTAL_BUDGET

for i in range(N):
    # Ràng buộc việc làm ròng không âm cho từng ngành
    model += (a1[i] - c1[i]*risk[i]) * x_AI[i] + b1[i] * x_H[i] >= 0
    # Ràng buộc năng lực đào tạo: Displaced <= RetrainCap
    # c1_i * risk_i * x_AI_i <= d1_i * x_H_i
    model += c1[i] * risk[i] * x_AI[i] <= d1[i] * x_H[i]

# 6. Giải bài toán
status = model.solve(pulp.PULP_CBC_CMD(msg=0))

# 7. Hiển thị kết quả
results_pulp = []
for i in range(N):
    val_ai = pulp.value(x_AI[i])
    val_h = pulp.value(x_H[i])
    nj = (a1[i] - c1[i]*risk[i]) * val_ai + b1[i] * val_h
    results_pulp.append({
        "Ngành": sectors_list[i],
        "Đầu tư AI (tỷ)": val_ai,
        "Đầu tư H (tỷ)": val_h,
        "NetJob": nj
    })

df_res = pd.DataFrame(results_pulp)
print(f"Trạng thái: {pulp.LpStatus[status]}")
print(f"Tổng NetJob tối ưu: {pulp.value(model.objective):,.2f}")
display(df_res)

def run_advanced_simulation(budget=30000, sector_cap=6500):
    # Sử dụng PuLP để tối ưu hóa với giới hạn trần (sector_cap)
    model = pulp.LpProblem("Advanced_Labor_Allocation", pulp.LpMaximize)
    x_ai_vars = [pulp.LpVariable(f"AI_{i}", 0, sector_cap) for i in range(N)]
    x_h_vars = [pulp.LpVariable(f"H_{i}", 0, sector_cap) for i in range(N)]

    # Mục tiêu
    model += pulp.lpSum([(a1[i] - c1[i]*risk[i])*x_ai_vars[i] + b1[i]*x_h_vars[i] for i in range(N)])

    # Ràng buộc ngân sách và đào tạo
    model += pulp.lpSum(x_ai_vars + x_h_vars) <= budget
    for i in range(N):
        model += c1[i]*risk[i]*x_ai_vars[i] <= d1[i]*x_h_vars[i]

    model.solve(pulp.PULP_CBC_CMD(msg=0))

    # Thu thập kết quả
    res_data = []
    for i in range(N):
        res_data.append({
            "Ngành": sectors_list[i],
            "AI_Inv": pulp.value(x_ai_vars[i]),
            "H_Inv": pulp.value(x_h_vars[i]),
            "NetJob": (a1[i] - c1[i]*risk[i])*pulp.value(x_ai_vars[i]) + b1[i]*pulp.value(x_h_vars[i])
        })
    return pd.DataFrame(res_data)

# Chạy mô phỏng và hiển thị kết quả
adv_results = run_advanced_simulation()
print("=== PHÂN BỔ CÓ GIỚI HẠN TRẦN (6,500 tỷ/ngành) ===")
display(adv_results.sort_values("NetJob", ascending=False))