# -*- coding: utf-8 -*-
"""câu 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XffG6aw5HHtJRV7v3y6XiZOc9CAEtawb
"""

!pip install pymoo
import numpy as np
from pymoo.core.problem import ElementwiseProblem
from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.optimize import minimize
import matplotlib.pyplot as plt

class VietnamDigitalProblem(ElementwiseProblem):
    def __init__(self):
        super().__init__(n_var=24, n_obj=4, n_ieq_constr=14, xl=np.zeros(24), xu=np.ones(24) * 12000)
        self.beta = np.array([
            [1.15, 0.85, 0.55, 1.30], [0.95, 1.25, 1.40, 1.05], [1.05, 0.95, 0.85, 1.15],
            [1.20, 0.75, 0.45, 1.35], [0.90, 1.30, 1.55, 1.00], [1.10, 0.85, 0.65, 1.25]
        ])
        self.e = np.array([0.42, 0.55, 0.48, 0.32, 0.62, 0.38])
        self.rho = np.array([0.18, 0.45, 0.28, 0.12, 0.52, 0.22])
        self.sig = np.array([0.32, 0.28, 0.30, 0.35, 0.25, 0.30])

    def _evaluate(self, x, out, *args, **kwargs):
        X = x.reshape(6, 4)
        f1 = -(self.beta * X).sum()
        region_sums = X.sum(axis=1)
        f2 = np.abs(region_sums - region_sums.mean()).mean()
        f3 = (self.e * (X[:, 0] + X[:, 2])).sum()
        f4 = (self.rho * X[:, 2]).sum() - (self.sig * X[:, 3]).sum()
        out["F"] = [f1, f2, f3, f4]
        g1 = X.sum() - 50000
        g2_7 = 5000 - region_sums
        g8_13 = region_sums - 12000
        g14 = 12000 - X[:, 3].sum()
        out["G"] = [g1] + g2_7.tolist() + g8_13.tolist() + [g14]

problem = VietnamDigitalProblem()
algorithm = NSGA2(pop_size=100)
res = minimize(problem, algorithm, ('n_gen', 200), seed=42, verbose=False)

F = res.F.copy()
F[:, 0] = -F[:, 0]

fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(12, 10))
ax1.scatter(F[:, 0], F[:, 1], color='blue', alpha=0.6)
ax1.set_xlabel('GDP Gain (f1)')
ax1.set_ylabel('Gini Index (f2)')
ax2.scatter(F[:, 0], F[:, 2], color='green', alpha=0.6)
ax2.set_xlabel('GDP Gain (f1)')
ax2.set_ylabel('Emissions (f3)')
ax3.scatter(F[:, 0], F[:, 3], color='red', alpha=0.6)
ax3.set_xlabel('GDP Gain (f1)')
ax3.set_ylabel('Net Risk (f4)')
ax4.scatter(F[:, 2], F[:, 3], color='purple', alpha=0.6)
ax4.set_xlabel('Emissions (f3)')
ax4.set_ylabel('Net Risk (f4)')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

# ---------------------------------------------------------
# BƯỚC 1: TRÍCH XUẤT QUẦN THỂ PARETO
# ---------------------------------------------------------

# res.F chứa giá trị các hàm mục tiêu của tập Pareto
# Nhớ nhân -1 cho f1 để đưa giá trị GDP gain về số dương thực tế
f1 = -res.F[:, 0]
f2 = res.F[:, 1]
f3 = res.F[:, 2]
f4 = res.F[:, 3]

# ---------------------------------------------------------
# BƯỚC 2: VẼ BIỂU ĐỒ SCATTER 3D (f1, f2, f3)
# ---------------------------------------------------------

fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# Vẽ các điểm nghiệm Pareto
scatter = ax.scatter(f1, f2, f3, c='blue', marker='o', alpha=0.6)

ax.set_title('Đường biên Pareto 3D:\nTăng trưởng (f1) - Bao trùm (f2) - Môi trường (f3)', fontsize=12)
ax.set_xlabel('GDP Gain (f1 - tỷ VND)', labelpad=10)
ax.set_ylabel('Bất bình đẳng Gini (f2)', labelpad=10)
ax.set_zlabel('Phát thải (f3)', labelpad=10)

plt.tight_layout()
plt.show()

# ---------------------------------------------------------
# BƯỚC 3: VẼ BIỂU ĐỒ PARALLEL COORDINATES (f1, f2, f3, f4)
# ---------------------------------------------------------

# Đưa dữ liệu vào DataFrame để dễ xử lý
df_pareto = pd.DataFrame({
    'Tăng trưởng GDP (Max)': f1,
    'Bất bình đẳng (Min)': f2,
    'Phát thải (Min)': f3,
    'Rủi ro An ninh (Min)': f4
})

# Chuẩn hóa Min-Max về khoảng [0, 1] để đồ thị không bị lệch thang đo
df_normalized = (df_pareto - df_pareto.min()) / (df_pareto.max() - df_pareto.min())

# Hàm parallel_coordinates của pandas cần một cột phân loại (class column)
df_normalized['Nghiệm'] = 'Pareto Solutions'

plt.figure(figsize=(12, 6))
pd.plotting.parallel_coordinates(
    df_normalized,
    class_column='Nghiệm',
    color='teal',
    alpha=0.3, # Để độ trong suốt thấp giúp nhìn rõ các vùng tập trung nghiệm
    linewidth=1.5
)

plt.title('Đánh đổi 4 mục tiêu chiến lược (Đã chuẩn hóa Min-Max 0-1)', fontsize=14)
plt.ylabel('Mức độ (0 = Tốt nhất/Thấp nhất, 1 = Kém nhất/Cao nhất)', fontsize=11)
plt.grid(True, linestyle='--', alpha=0.5)

# Ẩn chú giải (legend) vì chỉ có 1 nhóm nghiệm duy nhất
plt.gca().legend_.remove()

plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd

# ---------------------------------------------------------
# BƯỚC 0: CHUẨN BỊ MA TRẬN QUYẾT ĐỊNH
# ---------------------------------------------------------
# Trích xuất dữ liệu từ tập Pareto
f1_positive = -res.F[:, 0]  # Đưa GDP gain về giá trị dương thực tế
f2 = res.F[:, 1]
f3 = res.F[:, 2]
f4 = res.F[:, 3]

# Ghép thành ma trận quyết định X (mỗi hàng là 1 phương án, 4 cột là 4 mục tiêu)
X = np.column_stack((f1_positive, f2, f3, f4))

# Cài đặt trọng số và loại tiêu chí
weights = np.array([0.40, 0.25, 0.20, 0.15])
# True = Tiêu chí Lợi ích (Max), False = Tiêu chí Chi phí (Min)
is_benefit = np.array([True, False, False, False])

# ---------------------------------------------------------
# BƯỚC 1 & 2: CHUẨN HÓA VECTOR VÀ NHÂN TRỌNG SỐ
# ---------------------------------------------------------
# Chuẩn hóa vector theo cột
R = X / np.sqrt((X**2).sum(axis=0))

# Xây dựng ma trận chuẩn hóa có trọng số
V = R * weights

# ---------------------------------------------------------
# BƯỚC 3: XÁC ĐỊNH LỜI GIẢI LÝ TƯỞNG TỐT (A*) VÀ XẤU (A-)
# ---------------------------------------------------------
A_star = np.where(is_benefit, V.max(axis=0), V.min(axis=0))
A_neg = np.where(is_benefit, V.min(axis=0), V.max(axis=0))

# ---------------------------------------------------------
# BƯỚC 4: TÍNH KHOẢNG CÁCH EUCLIDE
# ---------------------------------------------------------
S_star = np.sqrt(((V - A_star)**2).sum(axis=1))
S_neg = np.sqrt(((V - A_neg)**2).sum(axis=1))

# ---------------------------------------------------------
# BƯỚC 5: TÍNH HỆ SỐ GẦN GŨI (C*) VÀ CHỌN NGHIỆM
# ---------------------------------------------------------
C_star = S_neg / (S_star + S_neg)

# Lấy ra chỉ số (index) của phương án có C* cao nhất
best_idx = np.argmax(C_star)

# ---------------------------------------------------------
# IN KẾT QUẢ NGHIỆM THỎA HIỆP
# ---------------------------------------------------------
print("=== NGHIỆM THỎA HIỆP TỐT NHẤT THEO TOPSIS ===")
print(f"Điểm TOPSIS (C*): {C_star[best_idx]:.4f}\n")

print("1. Đánh giá trên các mục tiêu chiến lược:")
print(f"   - Tăng trưởng (GDP Gain): {X[best_idx, 0]:,.2f} tỷ VND")
print(f"   - Bất bình đẳng (Gini):   {X[best_idx, 1]:.4f}")
print(f"   - Phát thải (CO2):        {X[best_idx, 2]:,.2f}")
print(f"   - Rủi ro an ninh ròng:    {X[best_idx, 3]:,.2f}\n")

print("2. Chiến lược phân bổ ngân sách tối ưu (Nghìn tỷ VND):")
best_allocation = res.X[best_idx].reshape(6, 4)

regions = ['Trung du MN phía Bắc', 'Đồng bằng sông Hồng', 'Bắc Trung Bộ & DH',
           'Tây Nguyên', 'Đông Nam Bộ', 'ĐBSCL']
items = ['Hạ tầng (I)', 'CDS (D)', 'Trí tuệ nhân tạo (AI)', 'Nhân lực (H)']

df_allocation = pd.DataFrame(best_allocation, index=regions, columns=items)
display(df_allocation.round(2))

import numpy as np

# Tìm index của phương án có GDP gain (cột 0) lớn nhất trong tập Pareto
max_growth_idx = np.argmax(X[:, 0])

# Trích xuất dữ liệu của 2 nghiệm
compromise_solution = X[best_idx]
max_growth_solution = X[max_growth_idx]

# 1. Tăng trưởng (Lợi ích thu thêm)
growth_gain_pct = (max_growth_solution[0] - compromise_solution[0]) / compromise_solution[0] * 100

# 2. Bao trùm xã hội / Gini (Chi phí phải trả - Tệ đi bao nhiêu %)
gini_sacrifice_pct = (max_growth_solution[1] - compromise_solution[1]) / compromise_solution[1] * 100

# 3. Môi trường / Phát thải (Chi phí phải trả - Tệ đi bao nhiêu %)
emission_sacrifice_pct = (max_growth_solution[2] - compromise_solution[2]) / compromise_solution[2] * 100

print("=== PHÂN TÍCH CHI PHÍ CƠ HỘI (TRADE-OFF ANALYSIS) ===")
print("So sánh: [Nghiệm Tăng trưởng Max] vs [Nghiệm Thỏa hiệp TOPSIS]\n")

print("1. Lợi ích Tăng trưởng (GDP Gain):")
print(f"   - Tăng từ: {compromise_solution[0]:,.2f} lên {max_growth_solution[0]:,.2f} tỷ VND.")
print(f"   => Lợi ích tăng thêm: +{growth_gain_pct:.2f}%\n")

print("2. Chi phí cơ hội về Bao trùm (Bất bình đẳng Gini):")
print(f"   - Bất bình đẳng tăng từ: {compromise_solution[1]:.4f} lên {max_growth_solution[1]:.4f}.")
print(f"   => Hi sinh (xấu đi): {gini_sacrifice_pct:.2f}%\n")

print("3. Chi phí cơ hội về Môi trường (Phát thải):")
print(f"   - Phát thải tăng từ: {compromise_solution[2]:,.2f} lên {max_growth_solution[2]:,.2f}.")
print(f"   => Hi sinh (xấu đi): {emission_sacrifice_pct:.2f}%")